### ISSUE TITLE
The attached map sometimes crashes the BW4T server

### ISSUE THREAD

**Issue by jzvandenoever** [eishub/BW4T#233]
The attached [map file](https://github.com/eishub/BW4T/files/2307615/ISO9.txt) sometimes crashes the environment. I'm not sure how likely it is but it loads successfully more often than it crashes.

Since the amount of blocks is static the error message confuses since it should be the same amount of blocks as before. When it happens it produces the following error:
```
goal.tools.errorhandling.exceptions.GOALRunFailedException: could not perform run of 'D:\Eclipse Workspace\BW4Trunner\agents\simple_single,map,agentcount.mas2g'.
        at goal.tools.AbstractRun.run(AbstractRun.java:197)
        at goal.BW4Trunner.Runner.process(Runner.java:42)
        at goal.BW4Trunner.BW4T.main(BW4T.java:106)
Caused by: java.lang.IllegalStateException: room is too small to fit more blocks
        at nl.tudelft.bw4t.server.repast.MapLoader.findFreePlace(MapLoader.java:466)
        at nl.tudelft.bw4t.server.repast.MapLoader.createBlocksForRoom(MapLoader.java:431)
        at nl.tudelft.bw4t.server.repast.MapLoader.placeBlocks(MapLoader.java:405)
        at nl.tudelft.bw4t.server.repast.MapLoader.loadMap(MapLoader.java:117)
        at nl.tudelft.bw4t.server.repast.MapLoader.contextChange(MapLoader.java:72)
        at nl.tudelft.bw4t.server.model.BW4TServerMap.notifyContextChange(BW4TServerMap.java:216)
        at nl.tudelft.bw4t.server.model.BW4TServerMap.setContext(BW4TServerMap.java:104)
        at nl.tudelft.bw4t.server.repast.BW4TBuilder.build(BW4TBuilder.java:30)
        at repast.simphony.dataLoader.engine.ClassNameContextBuilder.build(ClassNameContextBuilder.java:41)
        at repast.simphony.dataLoader.engine.DataLoaderControllerAction.runInitialize(DataLoaderControllerAction.java:48)
        at repast.simphony.engine.controller.DefaultController$2.visit(DefaultController.java:207)
        at repast.simphony.engine.controller.DefaultController$2.visit(DefaultController.java:1)
        at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:287)
        at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:290)
        at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:290)
        at repast.simphony.util.collections.NaryTree.preOrderTraversal(NaryTree.java:283)
        at repast.simphony.engine.controller.DefaultController.runInitialize(DefaultController.java:205)
        at repast.simphony.engine.controller.DefaultController.runInitialize(DefaultController.java:376)
        at nl.tudelft.bw4t.server.environment.BW4TRunner.runInitialize(BW4TRunner.java:74)
        at nl.tudelft.bw4t.server.environment.Stepper.<init>(Stepper.java:41)
        at nl.tudelft.bw4t.server.environment.BW4TEnvironment.launchRepast(BW4TEnvironment.java:342)
        at nl.tudelft.bw4t.server.environment.BW4TEnvironment.launchAll(BW4TEnvironment.java:310)
        at nl.tudelft.bw4t.server.environment.BW4TEnvironment.reset(BW4TEnvironment.java:601)
        at nl.tudelft.bw4t.server.environment.BW4TEnvironment.init(BW4TEnvironment.java:252)
        at nl.tudelft.bw4t.server.BW4TServer.requestInit(BW4TServer.java:425)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
        at sun.rmi.transport.Transport$1.run(Unknown Source)
        at sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Unknown Source)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(Unknown Source)
        at sun.rmi.transport.StreamRemoteCall.executeCall(Unknown Source)
        at sun.rmi.server.UnicastRef.invoke(Unknown Source)
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(Unknown Source)
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(Unknown Source)
        at com.sun.proxy.$Proxy2.requestInit(Unknown Source)
        at nl.tudelft.bw4t.client.BW4TClient.initServer(BW4TClient.java:549)
        at nl.tudelft.bw4t.client.environment.RemoteEnvironment.sendServerParams(RemoteEnvironment.java:138)
        at nl.tudelft.bw4t.client.environment.RemoteEnvironment.init(RemoteEnvironment.java:102)
        at goal.core.runtime.service.environmentport.EnvironmentPort.startPort(EnvironmentPort.java:107)
        at goal.core.runtime.service.environment.EnvironmentService.start(EnvironmentService.java:111)
        at goal.core.runtime.RuntimeManager.start(RuntimeManager.java:437)
        at goal.tools.AbstractRun.run(AbstractRun.java:183)
        ... 2 more
```

**Comment by jzvandenoever** [comment]
[This map](https://github.com/eishub/BW4T/files/2308207/ISO3.txt) crashes the server more consistently.

**Comment by Wouter1** [comment]
@koenhindriks ok. I think we can drop the minimum distance requirement now that we changed the specification (pickUp and atBlock are now multiple).

**Comment by Wouter1** [comment]
Zone only contains the list of BlockColor so no actual blocks there.

**Comment by Wouter1** [comment]
There currently is a junit test that checks that exception is thrown if we place too many blocks (MapLoaderTest#createBlocksForRoomNoRoomTest()

**Comment by Wouter1** [comment]
All junit tests are fine except those 3 that explicitly check distance between blocks.

But while testing the Human GUI I ran into the issue that I may be unable to see some blocks.

**Comment by Wouter1** [comment]
Discussed that with Koen. i suggest the solution that we can try say 10 times to place a block without overlap, and if that fails we put it anywhere in the room with some overlap with other blocks.

**Comment by Wouter1** [comment]
@koenhindriks  there appear more issues with the human GUI when blocks are overlapping

The main thing is that the GUI is designed assuming you can stand on at most one block.
So every menu item that reacts based on what block you are on now works only for the FIRST BLOCK of the pile you're standing on. 


So suppose you stand on a pile with white, green and red block. 

you get only "get white block" , "I am at white block", "room C2 contains a white block" etc. 

You would have to pick up the block and put it down somewhere else before you can get the other options. 

For now I assume that's the workaround we will have to recommend in the manual for such cases. 

Please advise if this is OK

**Comment by Wouter1** [comment]
I also found 2 other issues

1. When blocks overlap, the humanGUI and the server view show different top blocks. This is strange as both should use the same render code?

2. When you pick up and put down a block in the same room, the block disappears

**Comment by Wouter1** [comment]
Putting down a blcok you get this WARNING 
{{{

WARNING: request to perform 'putDown' was denied by the environment. because: performAction failed: ActException performAction failed:: RemoteException occurred in server thread; nested exception is: 
	java.rmi.RemoteException: action failed; nested exception is: 
	ActException type="failure" message="Action putDown with parameters [] failed to execute" cause="java.lang.IllegalArgumentException: Object 'nl.tudelft.bw4t.server.model.blocks.Block@1' must be added to the space's context before it can be moved": action failed; nested exception is: 
	ActException type="failure" message="Action putDown with parameters [] failed to execute" cause="java.lang.IllegalArgumentException: Object 'nl.tudelft.bw4t.server.model.blocks.Block@1' must be added to the space's context before it can be moved": Action putDown with parameters [] failed to execute: Object 'nl.tudelft.bw4t.server.model.blocks.Block@1' must be added to the space's context before it can be moved


}}}

**Comment by Wouter1** [comment]
This is strange, 392 is the official release and this should just be working?

**Comment by Wouter1** [comment]
It DOES work correctly with the official 392 release.

**Comment by Wouter1** [comment]
Checked with Vincent. develop works fine there. Reset and cleaned my workspace. Now it works fine here too ...

**Comment by Wouter1** [comment]
We call Block.addToContext but "Block@1" is not re-added because Repast thinks it's already in the context 

If you check the contents, (DefaultContext.addInternal) all Blocks are showing as "Block@1".

**Comment by Wouter1** [comment]
Wow, in Repast 2 blocks are equal if they have the same bbox and same servermap .....

**Comment by Wouter1** [comment]
It gives no problems if I put the blocks even .001 apart but when we have exactly the same doubles the problem occurs. This problem can occur both when adding and moving blocks. Maybe we can override BoundedMoveableObject.

**Comment by Wouter1** [comment]
raising to https://goalapl.atlassian.net/browse/ENV-1341

**Comment by Wouter1** [comment]
more on https://goalapl.atlassian.net/browse/ENV-1342

**Comment by Wouter1** [comment]
@koenhindriks @Venorcis  this has been fixed (on develop branch, not yet released)
